### ISSUE TITLE
What does this extension do?

### ISSUE THREAD

**Issue by mark-hahn** [mtsmfm/vscode-jscad-preview#1]
Subject says it all.

**Comment by mtsmfm** [comment]
@mark-hahn Thanks for your interest.
To be honest, I thought only I would use it, so I didn't write it down properly, but since I got an issue, I wrote an explanation.
If you still can't find how to use this extension, please let me know.

**Comment by mark-hahn** [comment]
It looks like something I could use.  I just have to figure out how to use
it.
